version: '2.2'
networks:
    mailnet:
        external:
            name: mailnet
services:
    mailhog:
        image: mailhog/mailhog:v1.0.0
        restart: always
        ports:
            - "127.0.0.1:8025:8025"
        networks:
            - mailnet
        environment:
            - MH_HOSTNAME=www01.fovea.cc

    hectane:
        image: hectane/hectane
        volumes:
            - ./hectane:/tmp/hectane
        networks:
            - mailnet
        environment:
            - DISABLE_SSL_VERIFICATION=1
        restart: always

    smtp:
        image: namshi/smtp
        restart: always
        networks:
            - mailnet
        environment:
            - MAILNAME=www01.fovea.cc
